"""add school active status

Revision ID: 11d71e64985b
Revises: 36bc36c4c82f
Create Date: 2026-06-15 09:34:10.718043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d71e64985b'
down_revision: Union[str, Sequence[str], None] = '36bc36c4c82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_availability', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'class_availability', 'schools', ['school_id'], ['id'])
    op.add_column('class_subjects', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'class_subjects', 'schools', ['school_id'], ['id'])
    op.add_column('schools', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'schools', ['name'])
    op.add_column('sections', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sections', 'schools', ['school_id'], ['id'])
    op.add_column('teacher_availability', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'teacher_availability', 'schools', ['school_id'], ['id'])
    op.add_column('teacher_subjects', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'teacher_subjects', 'schools', ['school_id'], ['id'])
    op.add_column('timetable_entries', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'timetable_entries', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable_entries', type_='foreignkey')
    op.drop_column('timetable_entries', 'school_id')
    op.drop_constraint(None, 'teacher_subjects', type_='foreignkey')
    op.drop_column('teacher_subjects', 'school_id')
    op.drop_constraint(None, 'teacher_availability', type_='foreignkey')
    op.drop_column('teacher_availability', 'school_id')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'school_id')
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'is_active')
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_column('class_subjects', 'school_id')
    op.drop_constraint(None, 'class_availability', type_='foreignkey')
    op.drop_column('class_availability', 'school_id')
    # ### end Alembic commands ###
