"""teacher improvements

Revision ID: 19d20a062320
Revises: 71542f0be21e
Create Date: 2026-06-17 09:14:08.851751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '19d20a062320'
down_revision: Union[str, Sequence[str], None] = '71542f0be21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('teacher_code', sa.String(length=50), nullable=True))
    op.add_column('teachers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('teachers', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'created_at')
    op.drop_column('teachers', 'is_active')
    op.drop_column('teachers', 'teacher_code')
    # ### end Alembic commands ###
