"""add section to class_subject

Revision ID: 36bc36c4c82f
Revises: bf170c16a6a3
Create Date: 2026-06-11 09:48:57.181774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bc36c4c82f'
down_revision: Union[str, Sequence[str], None] = 'bf170c16a6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_subjects', sa.Column('section_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'class_subjects', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_column('class_subjects', 'section_id')
    # ### end Alembic commands ###
