"""add teacher_id to class_subjects

Revision ID: e465b5b25d63
Revises: 09baccdf5d0c
Create Date: 2026-06-19 16:51:54.038696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e465b5b25d63'
down_revision: Union[str, Sequence[str], None] = '09baccdf5d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_subjects', sa.Column('teacher_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'class_subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_column('class_subjects', 'teacher_id')
    # ### end Alembic commands ###
